/*
  Warnings:

  - The values [VIEW_ORG,ONBOARD_USER,VIEW_WORKSPACE,CREATE_WORKSPACE,EDIT_WORKSPACE,DELETE_WORKSPACE,REMOVE_USER,CHANGE_USER_ROLE,EDIT_ORG,DELETE_ORG,CREATE_CUSTOM_ORG_ROLE,EDIT_CUSTOM_ORG_ROLE,DELETE_CUSTOM_ORG_ROLE] on the enum `OrgPermissionType` will be removed. If these variants are still used in the database, this will fail.
  - The values [VIEW_PROJECT,ALL_PROJECT,CREATE_PROJECT,EDIT_PROJECT,DELETE_PROJECT,VIEW_TASK,ALL_TASK,CREATE_TASK,EDIT_ANY_TASK,DELETE_TASK,ADD_MEMBER,REMOVE_MEMBER,CHANGE_MEMBER_ROLE,CREATE_EVENT,EDIT_EVENT,EDIT_ANY_EVENT,DELETE_EVENT,CREATE_CUSTOM_WORKSPACE_ROLE,EDIT_CUSTOM_WORKSPACE_ROLE,DELETE_CUSTOM_WORKSPACE_ROLE] on the enum `PermissionType` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "OrgPermissionType_new" AS ENUM ('OWNER', 'ORG_ALL', 'ORG_VIEW', 'ORG_EDIT', 'ORG_DELETE', 'ORG_ONBOARD_USER', 'ORG_REMOVE_USER', 'ORG_CHANGE_USER_ROLE', 'ORG_WORKSPACE_VIEW', 'ORG_WORKSPACE_CREATE', 'ORG_WORKSPACE_EDIT', 'ORG_WORKSPACE_DELETE', 'ORG_CUSTOM_ROLE_CREATE', 'ORG_CUSTOM_ROLE_EDIT', 'ORG_CUSTOM_ROLE_DELETE');
ALTER TYPE "OrgPermissionType" RENAME TO "OrgPermissionType_old";
ALTER TYPE "OrgPermissionType_new" RENAME TO "OrgPermissionType";
DROP TYPE "OrgPermissionType_old";
COMMIT;

-- AlterEnum
BEGIN;
CREATE TYPE "PermissionType_new" AS ENUM ('PROJECT_ALL', 'PROJECT_VIEW', 'PROJECT_CREATE', 'PROJECT_EDIT', 'PROJECT_DELETE', 'TASK_ALL', 'TASK_VIEW', 'TASK_CREATE', 'TASK_EDIT', 'TASK_DELETE', 'MEMBER_ADD', 'MEMBER_REMOVE', 'MEMBER_CHANGE_ROLE', 'EVENT_VIEW', 'EVENT_CREATE', 'EVENT_EDIT', 'EVENT_EDIT_ANY', 'EVENT_CANCEL', 'EVENT_DELETE', 'ROLE_WORKSPACE_CREATE', 'ROLE_WORKSPACE_EDIT', 'ROLE_WORKSPACE_DELETE', 'DEPARTMENT_ALL', 'DEPARTMENT_VIEW', 'DEPARTMENT_CREATE', 'DEPARTMENT_EDIT', 'DEPARTMENT_DELETE');
ALTER TYPE "PermissionType" RENAME TO "PermissionType_old";
ALTER TYPE "PermissionType_new" RENAME TO "PermissionType";
DROP TYPE "PermissionType_old";
COMMIT;
